message_publisher_node:
  ros__parameters:
    input_type: "reference_filter"
    topics:
      odometry: "nautilus/odom"
      waypoint: "nautilus/waypoint"
      reference_filter: "nautilus/guidance/dp_quat"
      output: "/utils/message_publisher"
